export const WW1_NAMES = {
  Turkey: 'Osmanlı İmparatorluğu',
  Russia: 'Çarlık Rusyası',
  Germany: 'Alman İmparatorluğu',
  Austria: 'Avusturya-Macaristan',
  Hungary: 'Avusturya-Macaristan',
  Czechia: 'Avusturya-Macaristan (Bohemya)',
  France: 'Fransa Cumhuriyeti',
  'United Kingdom': 'Büyük Britanya İmparatorluğu',
  Italy: 'İtalya Krallığı',
  Serbia: 'Sırbistan Krallığı',
  Bulgaria: 'Bulgaristan Çarlığı',
  Romania: 'Romanya Krallığı',
  Greece: 'Yunanistan Krallığı',
  Belgium: 'Belçika Krallığı',
  Montenegro: 'Karadağ Krallığı',
  Albania: 'Arnavutluk',
  Poland: 'Polonya (Rus Kontrolü)',
  Ukraine: 'Ukrayna (Rus Kontrolü)',
  Belarus: 'Belarus (Rus Kontrolü)',
  Finland: 'Finlandiya (Rus Kontrolü)',
  Estonia: 'Baltık (Rus Kontrolü)',
  Latvia: 'Baltık (Rus Kontrolü)',
  Lithuania: 'Baltık (Rus Kontrolü)',
  Jordan: 'Hicaz (Osmanlı)',
  Israel: 'Filistin (Osmanlı)',
  'Saudi Arabia': 'Arabistan (Osmanlı)',
  Morocco: 'Fas (Fransız Protektora)',
  Algeria: 'Cezayir (Fransız)',
  Tunisia: 'Tunus (Fransız)',
  Egypt: 'Mısır (İngiliz)',
  Sudan: 'Sudan (İngiliz-Mısır)',
  Iran: 'Persia (İran)',
  Afghanistan: 'Afganistan',
  India: 'Britanya Hindistanı',
  Pakistan: 'Britanya Hindistanı (Kuzeybatı)',
  Bangladesh: 'Britanya Hindistanı (Bengal)',
  'United States of America': 'Amerika Birleşik Devletleri',
  Canada: 'Kanada (Britanya Dominion)',
  Australia: 'Avustralya (Britanya Dominion)',
  'New Zealand': 'Yeni Zelanda (Britanya Dominion)',
  'South Africa': 'Güney Afrika (Britanya Dominion)',
  Japan: 'Japon İmparatorluğu',
  China: 'Çin İmparatorluğu',
  Portugal: 'Portekiz Krallığı',
  Spain: 'İspanya Krallığı',
  Netherlands: 'Hollanda Krallığı',
  Denmark: 'Danimarka Krallığı',
  Sweden: 'İsveç Krallığı',
  Norway: 'Norveç Krallığı',
  Switzerland: 'İsviçre Konfederasyonu',
  Georgia: 'Çarlık Rusyası (Kafkasya)',
  Armenia: 'Çarlık Rusyası (Kafkasya)',
  Azerbaijan: 'Çarlık Rusyası (Kafkasya)',
  Kazakhstan: 'Çarlık Rusyası (Orta Asya)',
  Uzbekistan: 'Çarlık Rusyası (Orta Asya)',
  Turkmenistan: 'Çarlık Rusyası (Orta Asya)',
  Kyrgyzstan: 'Çarlık Rusyası (Orta Asya)',
  Tajikistan: 'Çarlık Rusyası (Orta Asya)',
  Mongolia: 'Çarlık Rusyası (Nüfuz Alanı)',
  Moldova: 'Çarlık Rusyası (Bessarabya)',
  Slovenia: 'Avusturya-Macaristan',
  Croatia: 'Avusturya-Macaristan',
  'Bosnia and Herzegovina': 'Avusturya-Macaristan',
  Slovakia: 'Avusturya-Macaristan (Slovakya)',
  Kosovo: 'Osmanlı İmparatorluğu',
  'North Macedonia': 'Osmanlı İmparatorluğu (Makedonya)',
  Iraq: 'Osmanlı İmparatorluğu (Mezopotamya)',
  Syria: 'Osmanlı İmparatorluğu (Suriye)',
  Lebanon: 'Osmanlı İmparatorluğu (Lübnan)',
  Palestine: 'Osmanlı İmparatorluğu (Filistin)',
  Kuwait: 'Osmanlı İmparatorluğu (Kuveyt)',
  Yemen: 'Osmanlı İmparatorluğu (Yemen)',
  Eritrea: 'İtalya Krallığı (Sömürge)',
  Libya: 'İtalya Krallığı (Sömürge)',
  Somalia: 'İtalya Krallığı (Sömürge)',
  Djibouti: 'Fransa Cumhuriyeti (Sömürge)',
  Namibia: 'Alman İmparatorluğu (Sömürge)',
  Tanzania: 'Alman İmparatorluğu (Sömürge)',
  Cameroon: 'Alman İmparatorluğu (Sömürge)',
  Togo: 'Alman İmparatorluğu (Sömürge)',
  'British Empire': 'Büyük Britanya İmparatorluğu',
  'Ottoman Empire': 'Osmanlı İmparatorluğu',
  'United Kingdom of Great Britain and Ireland': 'Büyük Britanya İmparatorluğu',
  'Russian Empire': 'Çarlık Rusyası',
  'German Empire': 'Alman İmparatorluğu',
  'Austria-Hungary': 'Avusturya-Macaristan',
  'French Republic': 'Fransa Cumhuriyeti',
  'Kingdom of Italy': 'İtalya Krallığı',
  'Kingdom of Serbia': 'Sırbistan Krallığı',
  'Kingdom of Romania': 'Romanya Krallığı',
  'Kingdom of Bulgaria': 'Bulgaristan Çarlığı',
  'Kingdom of Greece': 'Yunanistan Krallığı',
  'Kingdom of Belgium': 'Belçika Krallığı',
  'Empire of Japan': 'Japon İmparatorluğu',
  'United States': 'Amerika Birleşik Devletleri',
  'British India': 'Britanya Hindistanı',
  Persia: 'Persia (İran)',
  Ethiopia: 'Habeşistan',
}

export function resolveCountryName(modernName) {
  return WW1_NAMES[modernName] ?? modernName
}

export const countryCoordinates = {
  'Osmanlı İmparatorluğu': [39, 35],
  'Osmanlı İmparatorluğu (Kuveyt)': [29.3, 47.9],
  'Osmanlı İmparatorluğu (Suriye)': [34, 38],
  'Osmanlı İmparatorluğu (Mezopotamya)': [33, 44],
  'Osmanlı İmparatorluğu (Lübnan)': [33.8, 35.9],
  'Osmanlı İmparatorluğu (Filistin)': [31.9, 35.2],
  'Osmanlı İmparatorluğu (Yemen)': [15.5, 44],
  'Osmanlı İmparatorluğu (Makedonya)': [41.6, 21.7],
  'Alman İmparatorluğu': [51, 10],
  'Alman İmparatorluğu (Sömürge)': [-6, 35],
  'Çarlık Rusyası': [60, 50],
  'Çarlık Rusyası (Kafkasya)': [42, 44],
  'Çarlık Rusyası (Orta Asya)': [43, 59],
  'Çarlık Rusyası (Nüfuz Alanı)': [47, 106],
  'Avusturya-Macaristan': [47, 16],
  'Avusturya-Macaristan (Bohemya)': [50, 15.5],
  'Avusturya-Macaristan (Slovakya)': [48.7, 19.5],
  'Büyük Britanya İmparatorluğu': [52, -1],
  'Fransa Cumhuriyeti': [46, 2],
  'Fransa Cumhuriyeti (Sömürge)': [14, 2],
  'İtalya Krallığı': [42, 12],
  'İtalya Krallığı (Sömürge)': [32, 13],
  'Japon İmparatorluğu': [36, 138],
  'Amerika Birleşik Devletleri': [38, -97],
  'Sırbistan Krallığı': [44, 21],
  'Romanya Krallığı': [45, 25],
  'Bulgaristan Çarlığı': [42, 25],
  'Yunanistan Krallığı': [39, 22],
  'Belçika Krallığı': [50, 4],
  'Britanya Hindistanı': [22, 78],
  'Britanya Hindistanı (Kuzeybatı)': [30, 70],
  'Britanya Hindistanı (Bengal)': [23, 90],
  'Polonya (Rus Kontrolü)': [52, 20],
  'Ukrayna (Rus Kontrolü)': [49, 32],
  'Belarus (Rus Kontrolü)': [53, 28],
  'Finlandiya (Rus Kontrolü)': [64, 26],
  'Baltık (Rus Kontrolü)': [57, 25],
  'Fas (Fransız Protektora)': [32, -6],
  'Mısır (İngiliz)': [26, 30],
  'Persia (İran)': [32, 53],
}
