/** Tüm olası harita bölgesi (WW1) adları — fetih sırasında savunmacının hangi bölgeleri kontrol ettiğini bulmak için */
module.exports = [...new Set([
    'Osmanlı İmparatorluğu',
    'Çarlık Rusyası',
    'Alman İmparatorluğu',
    'Avusturya-Macaristan',
    'Avusturya-Macaristan (Bohemya)',
    'Avusturya-Macaristan (Slovakya)',
    'Fransa Cumhuriyeti',
    'Fransa Cumhuriyeti (Sömürge)',
    'Büyük Britanya İmparatorluğu',
    'İtalya Krallığı',
    'İtalya Krallığı (Sömürge)',
    'Sırbistan Krallığı',
    'Bulgaristan Çarlığı',
    'Romanya Krallığı',
    'Yunanistan Krallığı',
    'Belçika Krallığı',
    'Karadağ Krallığı',
    'Arnavutluk',
    'Polonya (Rus Kontrolü)',
    'Ukrayna (Rus Kontrolü)',
    'Belarus (Rus Kontrolü)',
    'Finlandiya (Rus Kontrolü)',
    'Baltık (Rus Kontrolü)',
    'Hicaz (Osmanlı)',
    'Filistin (Osmanlı)',
    'Arabistan (Osmanlı)',
    'Fas (Fransız Protektora)',
    'Cezayir (Fransız)',
    'Tunus (Fransız)',
    'Mısır (İngiliz)',
    'Sudan (İngiliz-Mısır)',
    'Persia (İran)',
    'Afganistan',
    'Britanya Hindistanı',
    'Britanya Hindistanı (Kuzeybatı)',
    'Britanya Hindistanı (Bengal)',
    'Amerika Birleşik Devletleri',
    'Kanada (Britanya Dominion)',
    'Avustralya (Britanya Dominion)',
    'Yeni Zelanda (Britanya Dominion)',
    'Güney Afrika (Britanya Dominion)',
    'Japon İmparatorluğu',
    'Çin Cumhuriyeti',
    'Portekiz Krallığı',
    'İspanya Krallığı',
    'Hollanda Krallığı',
    'Danimarka Krallığı',
    'İsveç Krallığı',
    'Norveç Krallığı',
    'İsviçre Konfederasyonu',
    'Çarlık Rusyası (Kafkasya)',
    'Çarlık Rusyası (Orta Asya)',
    'Çarlık Rusyası (Nüfuz Alanı)',
    'Çarlık Rusyası (Bessarabya)',
    'Osmanlı İmparatorluğu (Makedonya)',
    'Osmanlı İmparatorluğu (Mezopotamya)',
    'Osmanlı İmparatorluğu (Suriye)',
    'Osmanlı İmparatorluğu (Lübnan)',
    'Osmanlı İmparatorluğu (Filistin)',
    'Osmanlı İmparatorluğu (Kuveyt)',
    'Osmanlı İmparatorluğu (Yemen)',
    'Alman İmparatorluğu (Sömürge)',
    'Habeşistan',
])];
